import {RoomEntityStruct} from '../../room/room.types';
import {UserBanEntityStruct} from '../bans/bans.types';
import {ClientType} from '@instinct-prj/interface';
import {GroupEntity} from '../../group/group.entity';
import {PhotoEntityStruct} from '../../photo/photo.types';
import {UserBadgesEntityStruct} from './user-badges.types';
import {RankEntityStruct} from '../../rank/rank.types';
import {BetaCodeEntity} from '../../beta-code/beta-code.entity';
import {PhotoReactionEntity} from '../../photo/photo-reaction.entity';

export interface UserEntityStruct {
  id?: number;
  username: string;
  realName?: string;
  password: string;
  email: string;
  mailVerified: number;
  accountCreated: number;
  accountDayOfBirth: number;
  lastLogin: number;
  lastOnline: number;
  motto?: string;
  figure: string;
  gender: string;
  rankID: number;
  rank?: RankEntityStruct;
  credits: number;
  pixels: number;
  points: number;
  online: '0' | '1' | '2';
  authTicket?: string;
  ipRegister: string;
  ipCurrent: string;
  machineID?: string;
  homeRoom: number;
  favoriteYoutubeVideo: string;
  userOfTheWeek: number;
  clientType: ClientType;
  stripeCustomerID?: string;
  photos?: PhotoEntityStruct[];
  rooms?: RoomEntityStruct[];
  badges?: UserBadgesEntityStruct[];
  friends?: UserEntityStruct[];
  groups?: GroupEntity[];
  joinedGroups?: GroupEntity[];
  bans?: UserBanEntityStruct[];
  betaCode?: BetaCodeEntity;
  reactions?: PhotoReactionEntity[];
}
